require: rubocop-rspec

# TBR = to be removed and fixed

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/**'
    - 'tmp/**/*'
    - 'storage/**/*'

Rails:
  Enabled: true

# TBR
Style/IfUnlessModifier:
  Enabled: false

# TBR
Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false


Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

# TBR
Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
