inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/**'

Rails:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
